serverless_region: 'us-east-1'
serverless_profile: 'stage'
serverless_service_name: 'logs'
account_id: '216297112034'
rds_user: ''
rds_password: ''
rds_host: ''
rds_port: '3306'
rds_db: 'logs'
SSM_KEY: 'api/rds'
